### ISSUE TITLE
Plans to develop Web DigiDoc

### ISSUE THREAD

**Issue by eidins** [web-eid/web-eid.js#19]
Are you planning to develop tools like https://github.com/PeculiarVentures/xadesjs to replace DigiDoc with a web version?

Latvia has eParaksts, but an open source alternative would be very attractive, especially if it supported other EU eID cards.

**Comment by Counter178** [comment]
At the moment there are no needs or plans to develop that kind of a solution to the web version.

**Comment by eidins** [comment]
Okay. I'm working on one. https://github.com/eidins/web-signer/blob/basic-app/src/App.js

It would be cool from a unification perspective. Standard easy way to sign documents internationally.

**Comment by mrts** [comment]
@eidins keep up the good work and keep us posted with comments in this ticket when it is ready!

**Comment by maltfield** [comment]
please no. For security reasons, I specifically try to keep as much out of the web browser as possible. Please do not deprecate dedicated apps that are compartimentalized away from the web browser (the biggest vector for malware).
