### ISSUE TITLE
Token signing

### ISSUE THREAD

**Issue by MarkoPomerants** [web-eid/web-eid.js#34]
Will there be support for **Token Signing** plugin? (Not all browser have web-eid)

Currently I get error:
`ExtensionUnavailableError: Web-eID extension is not available`

**Comment by kristelmerilain** [comment]
There is no plan to support Token Signing plugin since active development and management of the Token Signing has ended due to the transition to the new web authentication and signing solution (Web eID).

Could you please provide information on which browser you want to use?

**Comment by MarkoPomerants** [comment]
Chrome.

32-bit machines can't get the new web-eid app, I think?

**Comment by kristelmerilain** [comment]
Windows 32-bit operation system support was removed in July 2022 and there is no plan to add Windows 32-bit support to Web eID.
You can read more about it from here - https://www.id.ee/en/article/ria-updated-the-id-software/
