### ISSUE TITLE
Module not found: Error: Can't resolve '@web-eid/web-eid-library'

### ISSUE THREAD

**Issue by ydanneg** [web-eid/web-eid.js#39]
I have TS React project where I would like to use web-eid.js.

Dependency:
<img width="316" alt="Screenshot 2023-03-14 at 13 15 13" src="https://user-images.githubusercontent.com/32770915/224984576-86d96562-3424-408e-b369-4d486518b710.png">

Import:
<img width="282" alt="Screenshot 2023-03-14 at 13 10 55" src="https://user-images.githubusercontent.com/32770915/224984419-b7fc0c37-4a41-4ab9-bc05-87b12fc0d0e6.png">

I get an error:
<img width="1066" alt="Screenshot 2023-03-14 at 13 52 38" src="https://user-images.githubusercontent.com/32770915/224992883-6ad9eb30-3175-4479-ae7d-c75cf115c346.png">

I created a simple project to reproduce it: 
https://github.com/ydanneg/web-eid-sample

How can I use web-eid in my project?

PS. 
I'm not a web developer.

PPS.
Documentation seems to be outdated
<img width="873" alt="Screenshot 2023-03-14 at 13 55 01" src="https://user-images.githubusercontent.com/459303/224993539-961212ca-40f2-4cd2-a28d-a0c90a2e952e.png">

**Comment by vatsake** [comment]
For me, this works:
`import { getSigningCertificate, sign } from '@web-eid/web-eid-library/web-eid'`

**Comment by mrts** [comment]
Thanks for the tip, @vatsake! We intend to make the following work and update docs accordingly (**this is an example for the future that does not currently work**, for now, please use the API according to the example in @vatsake comment):

```js
import { getSigningCertificate, sign } from '@web-eid/web-eid-library'
```

However, as this is a minor developer experience issue, it is not top priority, so it will take some time until we get there. Feel free to upvote this.
