### ISSUE TITLE
Web eid auth with CloudFlare

### ISSUE THREAD

**Issue by MysteriousNothing** [web-eid/web-eid.js#49]
Hello, is it true that if you use CloudeFlare you can't use web-eid.js?

**Comment by mrts** [comment]
Vice-versa, Web eID authentication enables authentication regardless of TLS termination, proxy or gateway infrastructure as authentication is decoupled from the TLS layer (see [this](https://github.com/web-eid/web-eid-system-architecture-doc#authentication-1)). What makes you think so?

**Comment by MysteriousNothing** [comment]
Silly misunderstanding from who told me that. Just wanted to be sure.
