### ISSUE TITLE
Support for Belgium eID cards

### ISSUE THREAD

**Issue by nioperas06** [web-eid/web-eid.js#7]
Hi,
Thank you for this library ❤️ . I found this library while looking for web support of this [project](https://github.com/Fedict/eid-mw). So I'm here to ask I can add support for a new eID card (Belgium) to Web eID. Any guide to help me achieve this and contribute to this project? 

Thanks.

**Comment by mrts** [comment]
Hi @nioperas06 ! Really glad you found us, we would love to add Belgium eID support to Web eID!
We don't currently have enough man/womanpower to do it ourselves, so your support is very welcome.

We haven't yet had time to write a proper guide, but basically there are two ways to do it:

- Quick and dirty: add PKCS#11 module support with just a couple of lines, see example for Croatian eID support here: https://github.com/web-eid/libelectronic-id/pull/2/files. However, the result will be less stable than the second option and will require also Belgium eID middleware installation. It's a good path to start though.
- Deliberate and sound: add Belgium eID card APDUs. The result will be more stable and works without Belgium eID middleware. See example here: 
  - base class EIDIDEMIA: https://github.com/web-eid/libelectronic-id/blob/main/src/electronic-ids/pcsc/EIDIDEMIA.cpp
  - Estonian EstEID: https://github.com/web-eid/libelectronic-id/blob/main/src/electronic-ids/pcsc/EstEIDIDEMIA.cpp.

Please get in touch by email if you want to discuss this further (or feel free to comment below).

**Comment by mrts** [comment]
Hi @nioperas06! I'm really happy to announce that Belgium eID support will be part of the next release after v2.1.0. You can follow the progress here: https://github.com/web-eid/libelectronic-id/pull/31.
